# Generated by Django 5.0.6 on 2024-06-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_auth_user_username_auth_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='Date',
            field=models.CharField(max_length=11),
        ),
    ]
